[versions]
agp = "8.13.1"
appauth = "0.11.1"
browser = "1.9.0"
converterGson = "3.0.0"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleViewmodel = "2.10.0"
lombok = "1.18.20"
lombokVersion = "1.18.42"
material = "1.13.0"
activity = "1.12.0"
constraintlayout = "2.2.1"
okhttp = "5.3.2"
adsMobileSdk = "0.22.0-beta04"

[libraries]
appauth = { module = "net.openid:appauth", version.ref = "appauth" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
lombok = { module = "lombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
projectlombok-lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
ads-mobile-sdk = { group = "com.google.android.libraries.ads.mobile.sdk", name = "ads-mobile-sdk", version.ref = "adsMobileSdk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

